
export const FETCH_PRODUCERS_REQUEST= "FETCH_PRODUCERS_REQUEST"
export const FETCH_PRODUCERS_SUCCESS= "FETCH_PRODUCERS_SUCCESS"
export const FETCH_PRODUCERS_FAIL= "FETCH_PRODUCERS_FAIL"

export const NEW_PRODUCER_REQUEST = 'NEW_PRODUCER_REQUEST'
export const NEW_PRODUCER_SUCCESS = 'NEW_PRODUCER_SUCCESS'
export const NEW_PRODUCER_RESET = 'NEW_PRODUCER_RESET'
export const NEW_PRODUCER_FAIL = 'NEW_PRODUCER_FAIL'

export const UPDATE_PRODUCER_REQUEST = 'UPDATE_PRODUCER_REQUEST'
export const UPDATE_PRODUCER_SUCCESS = 'UPDATE_PRODUCER_SUCCESS'
export const UPDATE_PRODUCER_RESET = 'UPDATE_PRODUCER_RESET'
export const UPDATE_PRODUCER_FAIL = 'UPDATE_PRODUCER_FAIL'

export const DELETE_PRODUCER_REQUEST = 'DELETE_PRODUCER_REQUEST'
export const DELETE_PRODUCER_SUCCESS = 'DELETE_PRODUCER_SUCCESS'
export const DELETE_PRODUCER_RESET = 'DELETE_PRODUCER_RESET'
export const DELETE_PRODUCER_FAIL = 'DELETE_PRODUCER_FAIL'

export const PRODUCER_DETAILS_REQUEST = 'PRODUCER_DETAILS_REQUEST'
export const PRODUCER_DETAILS_SUCCESS = 'PRODUCER_DETAILS_SUCCESS'
export const PRODUCER_DETAILS_FAIL = 'PRODUCER_DETAILS_FAIL'

export const UPDATE_PRODUCER= "UPDATE_PRODUCER"
export const SELECTED_PRODUCER= "SELECTED_PRODUCER"
export const REMOVE_SELECTED_PRODUCER= "REMOVE_SELECTED_PRODUCER"

export const ADMIN_PRODUCERS_REQUEST = "ADMIN_PRODUCERS_REQUEST"
export const ADMIN_PRODUCERS_SUCCESS = "ADMIN_PRODUCERS_SUCCESS"
export const ADMIN_PRODUCERS_FAIL = "ADMIN_PRODUCERS_FAIL"

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
